// Code generated by mockery v1.0.0. DO NOT EDIT.

package autopilotevents

import (
	autopilot "github.com/hashicorp/raft-autopilot"
	mock "github.com/stretchr/testify/mock"
)

// MockAutopilot is an autogenerated mock type for the Autopilot type
type MockAutopilot struct {
	mock.Mock
}

// GetState provides a mock function with given fields:
func (_m *MockAutopilot) GetState() *autopilot.State {
	ret := _m.Called()

	var r0 *autopilot.State
	if rf, ok := ret.Get(0).(func() *autopilot.State); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autopilot.State)
		}
	}

	return r0
}
